---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - var_dump
      - codecept_debug
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/