language: php

env:
  global:
    - SYMFONY_ENV=test

php:
  - 5.6
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

install:
  - composer install -n --no-progress

script:
  - php bin/codecept run